#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.furnace','aj.furnace.root']}
execute as @e[type=minecraft:marker,tag=aj.furnace.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function furnace:summon/zzz/execute/2
function furnace:assert_animation_flags