#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.furnace.anim.desk_open] at @s run function furnace:animations/desk_open/next_frame
scoreboard players operation @s aj.furnace.animating = .aj.animation aj.furnace.animating