#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.furnace.bone.craftingtable] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.top] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.bottom] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.wood] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.outer2] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.inner3] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.inner4] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.open_small_top2] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.open_small_top] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.open_big_bottom] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.outer] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.inner1] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.inner2] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.furnace.bone.open_small_bottom] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~