#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#furnace:bone_entities,tag=aj.furnace.bone] if score @s aj.id = .this aj.id run function furnace:zzz/execute/8