#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.furnace.anim.desk_open
execute if score .aj.anim_loop aj.furnace.animating matches 0 run function furnace:animation_loop
scoreboard players set #execute aj.i 1