#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.furnace.anim.desk_open
execute if score .aj.furnace.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame 52
execute if score .aj.furnace.framerate aj.i matches 1.. run scoreboard players set @s aj.frame 0
scoreboard players add .noScripts aj.i 0
execute if score .aj.anim_loop aj.furnace.animating matches 0 run function furnace:animation_loop
scoreboard players set #execute aj.i 1