#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.furnace.desk_open.loopMode matches 0 run function furnace:animations/desk_open/stop
execute if score @s aj.furnace.desk_open.loopMode matches 1 run function furnace:animations/desk_open/pause
execute if score @s aj.furnace.desk_open.loopMode matches 2 run function furnace:animations/desk_open/zzz/execute/14