#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#furnace:bone_entities,tag=aj.furnace.bone,distance=..2.536] if score @s aj.id = .this aj.id run function furnace:animations/desk_open/tree/trunk
execute if score .noScripts aj.i matches 0 run function furnace:animations/desk_open/zzz/execute/13
scoreboard players operation @s aj.frame += .aj.furnace.framerate aj.i
scoreboard players set .aj.animation aj.furnace.animating 1
execute unless score @s aj.frame matches 0..52 run function furnace:animations/desk_open/edge