#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.furnace.root] at @s run function furnace:remove/zzz/conditional/0
execute if score #execute aj.i matches 0 run function furnace:remove/zzz/conditional/1