#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.furnace.bone.wood] run function furnace:animations/desk_open/tree/wood_display_top
execute if entity @s[tag=aj.furnace.bone.top] run function furnace:animations/desk_open/tree/top_display_top
execute if entity @s[tag=aj.furnace.bone.bottom] run function furnace:animations/desk_open/tree/bottom_display_top
execute if entity @s[tag=aj.furnace.bone.craftingtable] run function furnace:animations/desk_open/tree/craftingtable_display_top
execute if entity @s[tag=aj.furnace.bone.outer2] run function furnace:animations/desk_open/tree/outer2_display_top
execute if entity @s[tag=aj.furnace.bone.inner3] run function furnace:animations/desk_open/tree/inner3_display_top
execute if entity @s[tag=aj.furnace.bone.inner4] run function furnace:animations/desk_open/tree/inner4_display_top
execute if entity @s[tag=aj.furnace.bone.open_small_bottom] run function furnace:animations/desk_open/tree/open_small_bottom_display_top
execute if entity @s[tag=aj.furnace.bone.open_small_top2] run function furnace:animations/desk_open/tree/open_small_top2_display_top
execute if entity @s[tag=aj.furnace.bone.outer] run function furnace:animations/desk_open/tree/outer_display_top
execute if entity @s[tag=aj.furnace.bone.inner1] run function furnace:animations/desk_open/tree/inner1_display_top
execute if entity @s[tag=aj.furnace.bone.inner2] run function furnace:animations/desk_open/tree/inner2_display_top
execute if entity @s[tag=aj.furnace.bone.open_small_top] run function furnace:animations/desk_open/tree/open_small_top_display_top
execute if entity @s[tag=aj.furnace.bone.open_big_bottom] run function furnace:animations/desk_open/tree/open_big_bottom_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~