#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.5 ^-1.313 ^-0.746 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.5 ^-1.313 ^-0.723 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.5 ^-1.313 ^-0.701 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.5 ^-1.313 ^-0.679 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.5 ^-1.313 ^-0.659 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.5 ^-1.313 ^-0.639 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.5 ^-1.313 ^-0.62 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.5 ^-1.313 ^-0.601 ~ ~