#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.5 ^-1.313 ^-0.984 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.5 ^-1.313 ^-0.946 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.5 ^-1.313 ^-0.912 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.5 ^-1.313 ^-0.88 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.5 ^-1.313 ^-0.85 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.5 ^-1.313 ^-0.822 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.5 ^-1.313 ^-0.796 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.5 ^-1.313 ^-0.77 ~ ~