#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.5 ^-1.313 ^-0.581 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.5 ^-1.313 ^-0.573 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.5 ^-1.313 ^-0.565 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.5 ^-1.313 ^-0.557 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.5 ^-1.313 ^-0.55 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.5 ^-1.313 ^-0.543 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.5 ^-1.313 ^-0.537 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.5 ^-1.313 ^-0.531 ~ ~