#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^-1.313 ^-0.875 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.5 ^-1.313 ^-0.875 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.5 ^-1.313 ^-0.808 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.5 ^-1.313 ^-0.772 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.5 ^-1.313 ^-0.745 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.5 ^-1.313 ^-0.723 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.5 ^-1.313 ^-0.703 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.5 ^-1.313 ^-0.686 ~ ~