#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.5 ^-1.313 ^-1.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.5 ^-1.313 ^-1.247 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.5 ^-1.313 ^-1.23 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.5 ^-1.313 ^-1.19 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.5 ^-1.313 ^-1.129 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.5 ^-1.313 ^-1.054 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.5 ^-1.313 ^-0.968 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.5 ^-1.313 ^-0.875 ~ ~