#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.5 ^-1.313 ^-0.687 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.5 ^-1.313 ^-0.67 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.5 ^-1.313 ^-0.655 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.5 ^-1.313 ^-0.641 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.5 ^-1.313 ^-0.628 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.5 ^-1.313 ^-0.616 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.5 ^-1.313 ^-0.604 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.5 ^-1.313 ^-0.594 ~ ~