#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.5 ^-1.313 ^-0.584 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.5 ^-1.313 ^-0.575 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.5 ^-1.313 ^-0.566 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.5 ^-1.313 ^-0.558 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.5 ^-1.313 ^-0.55 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.5 ^-1.313 ^-0.542 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.5 ^-1.313 ^-0.535 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.5 ^-1.313 ^-0.529 ~ ~