#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.5 ^-1.313 ^-0.67 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.5 ^-1.313 ^-0.656 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.5 ^-1.313 ^-0.643 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.5 ^-1.313 ^-0.631 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.5 ^-1.313 ^-0.62 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.5 ^-1.313 ^-0.609 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.5 ^-1.313 ^-0.599 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.5 ^-1.313 ^-0.59 ~ ~