#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.5 ^-1.313 ^-0.525 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.5 ^-1.313 ^-0.52 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.5 ^-1.313 ^-0.515 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.5 ^-1.313 ^-0.51 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.5 ^-1.313 ^-0.506 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.5 ^-1.313 ^-0.502 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.5 ^-1.313 ^-0.5 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.5 ^-1.313 ^-0.5 ~ ~