#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.5 ^-1.313 ^-0.802 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.5 ^-1.313 ^-0.751 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.5 ^-1.313 ^-0.713 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.5 ^-1.313 ^-0.681 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.5 ^-1.313 ^-0.655 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.5 ^-1.313 ^-0.632 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.5 ^-1.313 ^-0.612 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.5 ^-1.313 ^-0.595 ~ ~