#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.5 ^-1.313 ^-0.58 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.5 ^-1.313 ^-0.567 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.5 ^-1.313 ^-0.555 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.5 ^-1.313 ^-0.545 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.5 ^-1.313 ^-0.536 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.5 ^-1.313 ^-0.528 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.5 ^-1.313 ^-0.521 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.5 ^-1.313 ^-0.515 ~ ~