#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-1.813 ^-0.246 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-1.813 ^-0.223 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-1.813 ^-0.201 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-1.813 ^-0.179 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-1.813 ^-0.159 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-1.813 ^-0.139 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-1.813 ^-0.12 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-1.813 ^-0.101 ~ ~